In [5]:
import pandas as pd

df = pd.read_excel("../../data/one_hop/preprocessed_df.xlsx")
df.fillna('null', inplace = True)
df

,index,subject,subject_id,sbj_one_hop,sbj_hop_num,obj_true,obj_true_id,obj_one_hop,obj_true_hop_num,obj_new,obj_new_id,obj_new_one_hop,obj_new_hop_num,view
0,0,Danielle Darrieux,Q234149,"human,film actor,Porfirio Rubirosa,Georges Mit...",20,French,Q150,"Vietnam,past imperative,Mali,participle,syllab...",72,English,Q1860,"simple present,Brunei,close back rounded vowel...",149,222931
1,1,Edwin of Northumbria,Q348955,"Whitby Abbey,human,Catholic saint,Cwenburh,Ger...",11,Christianity,Q5043,"Bible,christianisme,Jesus,Christian,hiristiyan...",17,Islam,Q432,"Battle of Uhud,Kaaba,Sufism,Dua,Jewish Encyclo...",68,177019
2,2,Toko Yasuda,Q7813654,"Japan,human,plvsvltramusic,rock music,bass gui...",12,guitar,Q6607,"body,machine head,Gitarre,Armenian Soviet Ency...",28,piano,Q5994,"klaver,Bartolomeo Cristofori,A,pianist,Klavier...",6,74330
3,3,Autonomous University of Madrid,Q788091,"Coalition for Advancing Research Assessment,Ag...",8,Spain,Q29,"La Rioja,Vietnam,Carlist Wars,Occitan,Immacula...",153,Sweden,Q34,"Iran,Kattegat,suedezi,Halland,Iraq,Swedish Emp...",136,87615
4,4,Lyon,Q456,"FRLIO,Gallia Lugdunensis,Lionano,Vaise,Jericho...",37,Beirut,Q3820,"Lebanon,Mousseitbeh,Ashrafieh,administrative t...",39,Manila,Q1461,"Nice,Pearl of the Orient,Philippines,Sacrament...",82,2376138
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21914,21914,Georges Bernier,Q3406819,"satirical magazine,human,Charlie Hebdo,voice,M...",21,French,Q150,"Vietnam,past imperative,Mali,participle,syllab...",84,Russian,Q7737,"genitive case,nominative case,voiceless alveol...",53,13177
21915,21915,Jean-Pierre Dionnet,Q968155,"television presenter,human,comics writer,male,...",6,French,Q150,"Vietnam,past imperative,Mali,participle,Madaga...",73,Spanish,Q1321,"spansk,nominative case,Panama,state,Philippine...",42,11530
21916,21916,Bong Jung-keun,Q50609,"human,South Korea,Atlanta Braves,Major League ...",9,pitcher,Q1048902,"lanceuse,softball,bowler,metalka",4,outfielder,Q1142885,"left fielder,center fielder,right fielder",3,12063
21917,21917,Umayyad Caliphate,Q8575586,"historical country,emeviler,Medieval Greek,Kin...",24,Damascus,Q3766,"Syria,Budapest,Ankara,WikiProject World Herita...",39,Athens,Q1524,"Kostas Bakoyannis,ateniesi,Athen,ZZ,XZ,IA,Tira...",104,4127429
21918,21918,Subair,Q7630724,"human,Kochi,Malayalam,India,Panoor Municipalit...",6,actor,Q33999,"acteur,glumica,glumac,ozuttelii,igralka,aktour...",62,composer,Q36834,"composed musical work,kompozistino,NNDB people...",44,41064

In [9]:
count = 0
for i in range(len(df)):
    if (len(df.loc[i, 'sbj_one_hop'].split(',')) != df.loc[i, 'sbj_hop_num'] or len(df.loc[i, 'obj_one_hop'].split(',')) != df.loc[i, 'obj_true_hop_num'] or len(df.loc[i, 'obj_new_one_hop'].split(',')) != df.loc[i, 'obj_new_hop_num']):
        count += 1
print(count)

553

In [15]:
list(df['sbj_hop_num'])

[20,
 11,
 12,
 8,
 37,
 18,
 9,
 5,
 13,
 4,
 8,
 13,
 12,
 4,
 9,
 12,
 227,
 6,
 3,
 14,
 5,
 11,
 3,
 9,
 5,
 0,
 12,
 5,
 1,
 28,
 25,
 5,
 34,
 4,
 18,
 3,
 15,
 1,
 2,
 5,
 34,
 12,
 11,
 1,
 20,
 26,
 13,
 19,
 4,
 1,
 5,
 0,
 19,
 5,
 6,
 24,
 1,
 10,
 46,
 9,
 9,
 14,
 4,
 9,
 10,
 13,
 1,
 13,
 5,
 11,
 38,
 2,
 5,
 21,
 21,
 7,
 27,
 1,
 14,
 22,
 7,
 20,
 1,
 3,
 18,
 18,
 15,
 17,
 10,
 3,
 20,
 16,
 8,
 6,
 3,
 2,
 6,
 3,
 2,
 3,
 33,
 11,
 4,
 14,
 2,
 4,
 25,
 21,
 14,
 2,
 3,
 42,
 34,
 25,
 8,
 1,
 12,
 7,
 0,
 8,
 5,
 1,
 7,
 9,
 32,
 0,
 11,
 6,
 1,
 4,
 5,
 19,
 14,
 5,
 24,
 3,
 21,
 1,
 8,
 1,
 4,
 10,
 2,
 39,
 42,
 44,
 1,
 4,
 1,
 2,
 5,
 1,
 30,
 20,
 2,
 1,
 9,
 38,
 5,
 9,
 2,
 1,
 12,
 3,
 6,
 5,
 20,
 28,
 39,
 24,
 19,
 10,
 8,
 25,
 12,
 7,
 23,
 3,
 8,
 23,
 24,
 14,
 20,
 31,
 2,
 7,
 5,
 0,
 3,
 7,
 256,
 4,
 3,
 26,
 35,
 2,
 34,
 17,
 55,
 1,
 19,
 24,
 4,
 8,
 24,
 3,
 12,
 2,
 0,
 13,
 7,
 41,
 3,
 58,
 10,
 9,
 7,
 9,
 7,
 9,
 17,
 0,
 1,
 17,
 16,
 16,
 11,
 8,
 1,
 16,
 5,
 261,
 18,
 2,
 7,
 14,
 12,
 8,
 7,
 1,
 2,
 4,
 7,
 8,
 36,
 1,
 10,
 13,
 18,
 11,
 21,
 1,
 21,
 8,
 130,
 6,
 22,
 20,
 3,
 1,
 3,
 9,
 23,
 13,
 2,
 42,
 209,
 23,
 21,
 16,
 3,
 39,
 35,
 6,
 14,
 7,
 15,
 3,
 1,
 3,
 8,
 0,
 41,
 6,
 13,
 0,
 10,
 24,
 0,
 20,
 1,
 13,
 36,
 3,
 1,
 3,
 8,
 18,
 10,
 19,
 5,
 4,
 2,
 4,
 19,
 2,
 49,
 4,
 2,
 26,
 3,
 13,
 15,
 6,
 45,
 20,
 13,
 8,
 7,
 7,
 34,
 20,
 0,
 6,
 50,
 1,
 2,
 24,
 13,
 111,
 7,
 7,
 4,
 10,
 2,
 20,
 1,
 2,
 5,
 27,
 4,
 17,
 8,
 3,
 26,
 13,
 11,
 13,
 43,
 3,
 7,
 5,
 7,
 37,
 0,
 11,
 4,
 13,
 21,
 1,
 4,
 61,
 12,
 8,
 14,
 6,
 2,
 187,
 8,
 11,
 7,
 35,
 10,
 14,
 17,
 1,
 12,
 9,
 4,
 5,
 30,
 5,
 16,
 2,
 17,
 22,
 13,
 13,
 9,
 22,
 35,
 13,
 9,
 7,
 2,
 8,
 42,
 0,
 70,
 1,
 2,
 1,
 8,
 6,
 4,
 1,
 9,
 14,
 8,
 4,
 27,
 1,
 20,
 8,
 39,
 9,
 3,
 7,
 4,
 2,
 37,
 5,
 1,
 0,
 10,
 9,
 11,
 12,
 20,
 9,
 11,
 59,
 42,
 39,
 37,
 9,
 13,
 8,
 9,
 16,
 24,
 10,
 1,
 13,
 3,
 3,
 3,
 10,
 6,
 33,
 6,
 5,
 3,
 11,
 6,
 3,
 6,
 7,
 5,
 1,
 7,
 3,
 16,
 154,
 20,
 37,
 9,
 9,
 8,
 9,
 57,
 1,
 13,
 2,
 7,
 13,
 6,
 21,
 2,
 29,
 2,
 2,
 12,
 5,
 19,
 0,
 14,
 32,
 56,
 1,
 14,
 14,
 7,
 2,
 43,
 10,
 7,
 10,
 7,
 46,
 5,
 2,
 8,
 7,
 4,
 3,
 27,
 5,
 7,
 9,
 7,
 16,
 17,
 84,
 1,
 10,
 4,
 4,
 3,
 4,
 4,
 12,
 9,
 42,
 3,
 1,
 15,
 22,
 9,
 33,
 5,
 4,
 13,
 20,
 4,
 13,
 9,
 10,
 3,
 8,
 8,
 4,
 1,
 31,
 9,
 21,
 50,
 9,
 24,
 1,
 4,
 3,
 7,
 16,
 41,
 8,
 7,
 3,
 2,
 2,
 5,
 22,
 17,
 4,
 5,
 26,
 2,
 2,
 6,
 9,
 1,
 2,
 8,
 9,
 19,
 3,
 3,
 29,
 2,
 15,
 19,
 4,
 2,
 29,
 8,
 23,
 42,
 9,
 14,
 2,
 8,
 2,
 7,
 7,
 29,
 10,
 19,
 14,
 43,
 4,
 6,
 23,
 9,
 26,
 33,
 3,
 14,
 30,
 16,
 16,
 1,
 9,
 25,
 4,
 10,
 9,
 1,
 5,
 8,
 28,
 3,
 6,
 7,
 18,
 4,
 12,
 2,
 4,
 8,
 16,
 12,
 5,
 22,
 7,
 11,
 19,
 0,
 1,
 6,
 6,
 2,
 6,
 21,
 5,
 10,
 11,
 12,
 16,
 8,
 5,
 8,
 2,
 2,
 11,
 23,
 14,
 1,
 2,
 2,
 1,
 6,
 1,
 1,
 24,
 5,
 12,
 8,
 73,
 5,
 3,
 15,
 5,
 8,
 10,
 8,
 14,
 23,
 10,
 5,
 18,
 15,
 16,
 9,
 23,
 2,
 18,
 4,
 32,
 2,
 11,
 7,
 1,
 10,
 40,
 6,
 10,
 12,
 21,
 16,
 60,
 219,
 108,
 4,
 7,
 50,
 15,
 3,
 11,
 0,
 4,
 0,
 9,
 52,
 2,
 22,
 3,
 1,
 19,
 2,
 21,
 4,
 11,
 96,
 3,
 41,
 1,
 3,
 4,
 10,
 14,
 41,
 3,
 2,
 10,
 7,
 2,
 10,
 17,
 1,
 1,
 9,
 2,
 8,
 4,
 1,
 10,
 15,
 14,
 36,
 10,
 181,
 8,
 7,
 17,
 4,
 1,
 10,
 8,
 9,
 8,
 6,
 2,
 10,
 9,
 17,
 3,
 21,
 3,
 17,
 24,
 11,
 3,
 10,
 9,
 9,
 4,
 4,
 11,
 8,
 29,
 10,
 182,
 0,
 3,
 17,
 6,
 3,
 3,
 19,
 1,
 13,
 31,
 7,
 1,
 1,
 8,
 1,
 8,
 8,
 87,
 0,
 12,
 12,
 21,
 28,
 4,
 5,
 7,
 2,
 77,
 9,
 10,
 25,
 49,
 11,
 54,
 11,
 8,
 16,
 0,
 13,
 22,
 900,
 11,
 8,
 11,
 8,
 66,
 15,
 4,
 5,
 16,
 23,
 22,
 13,
 7,
 1,
 4,
 38,
 8,
 7,
 9,
 4,
 20,
 7,
 8,
 26,
 17,
 13,
 31,
 4,
 9,
 8,
 4,
 6,
 4,
 12,
 12,
 9,
 2,
 9,
 43,
 6,
 29,
 8,
 41,
 193,
 11,
 0,
 19,
 25,
 2,
 7,
 35,
 35,
 108,
 16,
 38,
 5,
 7,
 7,
 2,
 40,
 1,
 3,
 3,
 15,
 24,
 13,
 28,
 17,
 13,
 10,
 18,
 21,
 14,
 26,
 63,
 9,
 36,
 17,
 21,
 16,
 27,
 10,
 28,
 19,
 7,
 16,
 1,
 13,
 1,
 2,
 12,
 18,
 5,
 5,
 14,
 14,
 3,
 7,
 7,
 6,
 14,
 29,
 2,
 1,
 3,
 8,
 26,
 68,
 24,
 19,
 111,
 1,
 6,
 2,
 11,
 9,
 2,
 13,
 5,
 2,
 1,
 1,
 72,
 8,
 81,
 1,
 1,
 12,
 33,
 26,
 5,
 9,
 3,
 37,
 24,
 15,
 24,
 24,
 8,
 9,
 58,
 40,
 17,
 14,
 6,
 9,
 3,
 0,
 2,
 6,
 30,
 0,
 1,
 10,
 1,
 103,
 30,
 22,
 14,
 5,
 14,
 4,
 7,
 11,
 14,
 46,
 23,
 19,
 13,
 4,
 6,
 9,
 3,
 3,
 13,
 19,
 34,
 ...]

In [23]:
check = ["sbj_hop_num", 'obj_true_hop_num', 'obj_new_hop_num']

def stat(df, word, k):
    count = 0
    word_list = list(df[word])
    for freq in word_list:
        if freq >= k:
            count += 1
    print(f'Word count : {count} ({round(count / len(word_list)*100,2)}%) with {word} >= {k}')
    return count

for i in range(0, 11):
    stat(df, check[0], i)
    
for i in range(0, 11):
    stat(df, check[1], i)

for i in range(0, 11):
    stat(df, check[2], i)

Word count : 21919 (100.0%) with sbj_hop_num >= 0
Word count : 21420 (97.72%) with sbj_hop_num >= 1
Word count : 20066 (91.55%) with sbj_hop_num >= 2
Word count : 18619 (84.94%) with sbj_hop_num >= 3
Word count : 17227 (78.59%) with sbj_hop_num >= 4
Word count : 16055 (73.25%) with sbj_hop_num >= 5
Word count : 14937 (68.15%) with sbj_hop_num >= 6
Word count : 13920 (63.51%) with sbj_hop_num >= 7
Word count : 12901 (58.86%) with sbj_hop_num >= 8
Word count : 11883 (54.21%) with sbj_hop_num >= 9
Word count : 10885 (49.66%) with sbj_hop_num >= 10
Word count : 21919 (100.0%) with obj_true_hop_num >= 0
Word count : 21882 (99.83%) with obj_true_hop_num >= 1
Word count : 21775 (99.34%) with obj_true_hop_num >= 2
Word count : 21643 (98.74%) with obj_true_hop_num >= 3
Word count : 21393 (97.6%) with obj_true_hop_num >= 4
Word count : 21314 (97.24%) with obj_true_hop_num >= 5
Word count : 20942 (95.54%) with obj_true_hop_num >= 6
Word count : 20364 (92.91%) with obj_true_hop_num >= 7
Word count : 19583 (89.34%) with obj_true_hop_num >= 8
Word count : 19441 (88.69%) with obj_true_hop_num >= 9
Word count : 19149 (87.36%) with obj_true_hop_num >= 10
Word count : 21919 (100.0%) with obj_new_hop_num >= 0
Word count : 21884 (99.84%) with obj_new_hop_num >= 1
Word count : 21855 (99.71%) with obj_new_hop_num >= 2
Word count : 21628 (98.67%) with obj_new_hop_num >= 3
Word count : 21564 (98.38%) with obj_new_hop_num >= 4
Word count : 21293 (97.14%) with obj_new_hop_num >= 5
Word count : 21129 (96.4%) with obj_new_hop_num >= 6
Word count : 20732 (94.58%) with obj_new_hop_num >= 7
Word count : 20169 (92.02%) with obj_new_hop_num >= 8
Word count : 19831 (90.47%) with obj_new_hop_num >= 9
Word count : 19207 (87.63%) with obj_new_hop_num >= 10

In [25]:
check = ["sbj_hop_num", 'obj_true_hop_num', 'obj_new_hop_num']

def stat2(df, word, k):
    count = 0
    sbj_list = list(df[word[0]])
    obj_list = list(df[word[1]])
    obj_new_list = list(df[word[2]])
    for i in range(len(sbj_list)):
        if sbj_list[i] >= k and obj_list[i] >= k and obj_new_list[i] >= k:
            count += 1
    print(f'Word count : {count} ({round(count / len(sbj_list)*100,2)}%) with triplet >= {k}')
    return count

for i in range(0, 11):
    stat2(df, check, i)

Word count : 21919 (100.0%) with triplet >= 0
Word count : 21366 (97.48%) with triplet >= 1
Word count : 19878 (90.69%) with triplet >= 2
Word count : 18146 (82.79%) with triplet >= 3
Word count : 16515 (75.35%) with triplet >= 4
Word count : 15083 (68.81%) with triplet >= 5
Word count : 13622 (62.15%) with triplet >= 6
Word count : 12018 (54.83%) with triplet >= 7
Word count : 10578 (48.26%) with triplet >= 8
Word count : 9649 (44.02%) with triplet >= 9
Word count : 8708 (39.73%) with triplet >= 10